<h1>
    <b>POSTTEST 7</b>
</h1>
<h3>
    Kecerdasan Buatan
</h3>

<p>
    Nama : Tegar Fitrah Naba Atthoriq
    <br>
    NIM : 2009106085
</p>
<hr>

<h2>
    <b>Tensorflow Basic</b>
</h2>
<p>
    sebelum masuk ke posttest kali ini, ada beberapa hal yang perlu dilakukan yaitu :
</p>
<p>
    a. Import library yang akan digunakan untuk posttest kali ini
</p>

In [16]:
import tensorflow as tf

<h3><b>1. Membuat Tensor</b></h3>

<p>
    a. Nilai random
</p>

In [17]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1.0, seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.28433853,  0.8922832 ,  0.8983451 ,  0.7163981 ,  0.34969485],
       [-0.37960768,  0.01531979,  0.27423722, -2.214901  , -0.08514621],
       [ 1.0113182 ,  0.6616626 ,  1.383323  , -0.40465203,  0.86142987],
       [-0.12589967, -1.418615  ,  2.0295074 ,  0.15304402,  0.13658497],
       [-0.49787143,  0.38847125, -0.4244715 ,  0.46214256, -0.5444318 ]],
      dtype=float32)>

<p>
    a. Nilai random
</p>

In [18]:
pri_list = [[2, 3, 5, 7, 11],
            [13, 17, 19, 23, 29],
            [31, 37, 41, 43, 47],
            [53, 59, 61, 67, 71],
            [73, 79, 83, 89, 97]]

prime_tensor = tf.convert_to_tensor(pri_list, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

<h3><b>3. Menampilkan Dimensi</b></h3>

In [19]:
print(random_tensor.get_shape())
print(prime_tensor.get_shape())

(5, 5)
(5, 5)


<h3><b>4. Proses Aritmetika</b></h3>

In [20]:
print("Penjumlahan :\n", tf.add(random_tensor, prime_tensor))
print("Pengurangan :\n", tf.subtract(random_tensor, prime_tensor))
print("Perkalian :\n", tf.multiply(random_tensor, prime_tensor))
print("Pembagian :\n", tf.divide(random_tensor, prime_tensor))
print("Pangkat :\n", tf.pow(random_tensor, prime_tensor))

Penjumlahan :
 tf.Tensor(
[[ 1.7156615  3.8922832  5.898345   7.7163982 11.349695 ]
 [12.620392  17.01532   19.274237  20.785099  28.914854 ]
 [32.01132   37.661663  42.383324  42.59535   47.86143  ]
 [52.8741    57.581387  63.029507  67.153046  71.13658  ]
 [72.50213   79.38847   82.57553   89.46214   96.45557  ]], shape=(5, 5), dtype=float32)
Pengurangan :
 tf.Tensor(
[[ -2.2843385  -2.1077168  -4.101655   -6.2836018 -10.650305 ]
 [-13.379608  -16.98468   -18.725763  -25.214901  -29.085146 ]
 [-29.988682  -36.338337  -39.616676  -43.40465   -46.13857  ]
 [-53.1259    -60.418613  -58.970493  -66.846954  -70.86342  ]
 [-73.49787   -78.61153   -83.42447   -88.53786   -97.54443  ]], shape=(5, 5), dtype=float32)
Perkalian :
 tf.Tensor(
[[ -0.56867707   2.6768496    4.4917254    5.0147867    3.8466434 ]
 [ -4.9349       0.2604365    5.210507   -50.942722    -2.4692402 ]
 [ 31.350864    24.481516    56.71624    -17.400038    40.487206  ]
 [ -6.672683   -83.69828    123.79995     10.253949  

<h3><b>5. Nilai Max dan Min</b></h3>

In [21]:
print("Nilai Max : ", tf.argmax(random_tensor, axis=0))
print("Nilai Min : ", tf.argmin(random_tensor, axis=0))

Nilai Max :  tf.Tensor([2 0 3 0 2], shape=(5,), dtype=int64)
Nilai Min :  tf.Tensor([4 3 4 1 4], shape=(5,), dtype=int64)


<h3><b>6. Penggabungan</b></h3>

In [22]:
print("Hasil Penggabungan :\n", tf.concat([random_tensor, prime_tensor], axis=0))

Hasil Penggabungan :
 tf.Tensor(
[[-2.8433853e-01  8.9228320e-01  8.9834511e-01  7.1639812e-01
   3.4969485e-01]
 [-3.7960768e-01  1.5319794e-02  2.7423722e-01 -2.2149010e+00
  -8.5146211e-02]
 [ 1.0113182e+00  6.6166258e-01  1.3833230e+00 -4.0465203e-01
   8.6142987e-01]
 [-1.2589967e-01 -1.4186150e+00  2.0295074e+00  1.5304402e-01
   1.3658497e-01]
 [-4.9787143e-01  3.8847125e-01 -4.2447150e-01  4.6214256e-01
  -5.4443181e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]], shape=(10, 5), dtype=float32)


<h3><b>7. Sorting (Descending)</b></h3>

In [23]:
print(tf.sort(random_tensor, direction='DESCENDING', axis=1))
print(tf.sort(prime_tensor, direction='DESCENDING', axis=1))

tf.Tensor(
[[ 0.8983451   0.8922832   0.7163981   0.34969485 -0.28433853]
 [ 0.27423722  0.01531979 -0.08514621 -0.37960768 -2.214901  ]
 [ 1.383323    1.0113182   0.86142987  0.6616626  -0.40465203]
 [ 2.0295074   0.15304402  0.13658497 -0.12589967 -1.418615  ]
 [ 0.46214256  0.38847125 -0.4244715  -0.49787143 -0.5444318 ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
